services:
  fastapi:
    image: fastapi:dev
    volumes:
      - ./fastapi/app:/code/app
    ports:
      - "33567:81"
    networks:
      - x61ctfnetwork
  postgres:
    image: postgres:dev
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

networks:
  x61ctfnetwork:
    external: true
