services:
  fastapi:
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    image: fastapi:dev
    networks:
      - x61ctfnetwork
    volumes:
      - ./fastapi/app:/code/app
    ports:
      - "33567:81"
  postgres:
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    image: postgres:dev
    networks:
      - x61ctfnetwork
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: x61ctf
      POSTGRES_DB: x61ctf
      POSTGRES_PASSWORD: changeme 
networks:
  x61ctfnetwork:
    external: true
volumes:
  postgres_data:
